#pragma config(Sensor, S2, c1, sensorEV3_Color)
#pragma config(Sensor, S3, c2, sensorEV3_Color)
#pragma config(Motor, motorB, rm, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, lm, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, mm, tmotorEV3_Medium, PIDControl, encoder)

//!!Code automatically generated by ‘ROBOTC’ configuration wizard !!//

int calcBound2(){ 
    int bound; 
    int black = 0; 
    int white = 0;
    for(int i=0 ; i<5 ; i++){ 
        black+=getColorReflected(c1); 
        black+=getColorReflected(c2); sleep(10); 
    }

    setMotorSpeed(lm,20); 
    setMotorSpeed(rm,20); 
    sleep(500); 
    setMotorSpeed(lm,0); 
    setMotorSpeed(rm,0);

    for(int i=0 ; i<5 ; i++){ 
        white+=getColorReflected(c1); 
        white+=getColorReflected(c2); 
        sleep(10); 
    }

    bound = (white/10 + black/10)/2;
    return bound; 
}

void stop(){ 
    setMotorSpeed(lm,0); 
    setMotorSpeed(rm,0); 
}

void domino(){ 
    moveMotorTarget(mm,360,-10);
}

task main(){ 
    int gray = calcBound2(); 
    //sleep(5000); 
    while(1){ 
        int left = getColorReflected(c1); 
        int right = getColorReflected(c2);

        if(left>=gray && right>= gray){
         setMotorSpeed(lm,20);
         setMotorSpeed(rm,22);
        }
        else if(left>=gray && right<gray){
         setMotorSpeed(lm,-5);
         setMotorSpeed(rm,10);
        }
        else if(left<gray && right>=gray){
         setMotorSpeed(lm,10);
         setMotorSpeed(rm,-5);
        }
        else{
         setMotorSpeed(lm,0);
         setMotorSpeed(rm,0);
        }

        sleep(500);
        stop();
        domino();
        sleep(3000);
    }
}